name: Go Continuous Integration

# This workflow runs on pushes to the 'main' branch and on any pull request that targets the 'main' branch.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.0'

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Install dependencies
        run: go mod download

      - name: Run linter
        uses: golangci/golangci-lint-action@v6
        with:
          version: 'latest'
          only-new-issues: true

      - name: Run tests with race detector
        run: go test -v -race -tags fts5 ./...

      - name: Build the application
        run: go build -v -tags fts5 -o yib .